// Auto-generated by scripts/generate-version.js
export const BUILD_METADATA = {
  "app": "dustguard",
  "commit": "747667f227862570c34138ee1c913d5cc0bdf240",
  "buildTime": "2026-09-06T23:50:29.144Z",
  "environment": "production"
};
