// Auto-generated by scripts/generate-version.js
export const BUILD_METADATA = {
  "app": "dustguard",
  "commit": "8be9c12559e4f43dbeb3379b8a01e40e57ebb2d1",
  "buildTime": "2026-09-06T15:41:12.782Z",
  "environment": "production"
} as const;
