// Auto-generated by scripts/generate-version.js
export const BUILD_METADATA = {
  "app": "dustguard",
  "commit": "43408c3d7c9931497d3d591b396fe9cb4129183b",
  "buildTime": "2026-09-06T07:02:09.033Z",
  "environment": "production"
} as const;
