// Auto-generated by scripts/generate-version.js
export const BUILD_METADATA = {
  "app": "dustguard",
  "commit": "511dcefa5bbd2f94e9fc96f56e53b526b139f0aa",
  "buildTime": "2026-09-06T08:46:56.321Z",
  "environment": "production"
} as const;
