// Auto-generated by scripts/generate-version.js
export const BUILD_METADATA = {
  "app": "dustguard",
  "commit": "b9bf6eb0e1751373b2f62770f464eafbdfa3b5a8",
  "buildTime": "2026-09-06T15:55:20.997Z",
  "environment": "production"
};
