// Auto-generated by scripts/generate-version.js
export const BUILD_METADATA = {
  "app": "dustguard",
  "commit": "a7082793a45516563d00e6efc7635d33824d3c81",
  "buildTime": "2026-09-06T17:15:07.346Z",
  "environment": "production"
};
