import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

let commit = 'unknown';
try {
  commit = execSync('git rev-parse HEAD', { cwd: rootDir, encoding: 'utf8' }).trim();
} catch (e) {
  commit = process.env.CF_PAGES_COMMIT_SHA || process.env.COMMIT_SHA || 'dev';
}

const buildTime = new Date().toISOString();
const metadata = {
  app: 'dustguard',
  commit,
  buildTime,
  environment: 'production'
};

const serverDir = path.join(rootDir, 'server');
if (!fs.existsSync(serverDir)) {
  fs.mkdirSync(serverDir, { recursive: true });
}

const versionTsPath = path.join(serverDir, 'version.ts');
const content = `// Auto-generated by scripts/generate-version.js
export const BUILD_METADATA = ${JSON.stringify(metadata, null, 2)} as const;
`;

fs.writeFileSync(versionTsPath, content, 'utf8');
console.log(`✓ Version metadata generated: commit=${commit}, buildTime=${buildTime}`);
